name: ll_project
type: python:3.10

relationships:
    database: "db:postgresql"

#应用暴露网路
web:
    upstream:
      socket_family: unix
    commands:
      start: "gunicorn -w 4 -b unix:$SOCKET ll_project.wsgi:application"
    locations:
      "/":
        passthru: true
      "/static":
        root: "static"
        expires: 1h
        allow: true

#应用磁盘大小
disk: 512

#设置本地挂载
mounts:
  "logs":
    source: "local"
    source_path: logs

# 设置构建和部署钩子
hooks:
  build: | 
    pip install --upgrade pip
    pip install -r requirements.txt
    pip install -r requirements-remote.txt

    mkdir logs
    python manage.py collectstatic
    rm -rf logs

  deploy: |
    python manage.py migrate
       

    
      
         

