services:
  - type: web
    name: ll-project
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ll_project.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ll-project.onrender.com
